In [4]:
import numpy as np
X = np.random.normal(loc=1, scale= 10, size = (1000,50)) # Генерация матрицы с нормальным распределением с заданными средним и дисперсией
m = np.mean(X,axis = 0) # вычисление среднего
std = np.std (X, axis = 0) # вычисление дисперсии
X_norm = ((X-m)/std) # получение нормированной матрицы
print (X_norm)

[[ 0.42934325 -0.25966728 -0.26283477 ...  1.35088366  0.38508011
   0.9256431 ]
 [ 0.78361236 -1.25000813 -0.52471511 ... -0.95269013  0.31357198
   2.61425357]
 [ 0.34171582 -1.68943882 -0.02024151 ... -1.14763481 -0.20872695
  -1.80666867]
 ...
 [ 2.82249761  0.87561951  1.14203484 ...  0.67710016 -0.6931354
  -0.82627236]
 [-1.74150025 -0.62312262  1.94690271 ... -1.99466825 -0.40281997
  -0.66980722]
 [ 1.15968379  0.44000121 -0.38147113 ...  0.85356459  0.53690542
  -1.69926158]]


In [9]:
Z = np.array ([[4,5,0],
              [2,1,8],
             [9,8,7],
             [4,5,1],
              [2,2,8],
              [1,5,8]])
s = np.sum(Z, axis =1) # сумма  по строкам
print (np.nonzero(s>10))

(array([1, 2, 4, 5], dtype=int64),)


In [11]:
A = np.eye(3) # создание единичной матрицы
B = np.eye(3)
print (A)
print(B)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
AB = np.vstack((A,B)) # вертикальная стыковка матриц
print(AB)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
